name: 'Support question ❔'
description: I can't find a solution to my problem with MUI Design kit.
title: "[question] "
labels: ['status: waiting for maintainer', 'support: question']
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        ⚠️ **Don't use this form if the problem is [a bug](https://github.com/mui/mui-design-kits/issues/new?assignees=&labels=status%3A+needs+triage&template=1.bug.yml) or a [feature request](https://github.com/mui/mui-design-kits/issues/new?assignees=&labels=status%3A+needs+triage&template=2.feature.yml), use the dedicated form instead.**
  - type: checkboxes
    attributes:
      label: Duplicates
      description: Please [search the history](https://github.com/mui/mui-design-kits/issues) to see if an issue already exists for the same problem.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested the latest version
          required: true
  - type: textarea
    attributes:
      label: The problem in depth 🔍
  - type: textarea
    attributes:
      label: Your environment 🌎
      description: The version of the design file you are using. The version is usually disabled in the footer of the design frames.
